import localFont from 'next/font/local'
 
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const erodeLight = localFont({
  src:"../../public/assets/fonts/Erode-Light.woff2",
  weight:'300',
  display:'swap',
  variable:"--font-erode-light",
})

const erodeRegular = localFont({
  src:"../../public/assets/fonts/Erode-Regular.woff2",
  weight:'400',
  display:'swap',
  variable:"--font-erode-regular",
})

const erodeBold = localFont({
  src:"../../public/assets/fonts/Erode-Bold.woff2",
  weight:'700',
  display:'swap',
  variable:"--font-erode-bold",
})

export const metadata = {
  title: "Meet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${erodeLight.variable} ${erodeRegular.variable} ${erodeBold.variable} antialiased font-erodeRegular bg-stone-800`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
